### ISSUE TITLE
Scrollable in-game chat For Connivence??? 

### ISSUE THREAD

**Issue by ghost** [Luka967/Cigar#106]
Popsplit.us Has this . 
How can i make the chat in this client scrollable? 
@Luka967, Im sure it would be convenient for the users. ,
Thenks!

**Comment by Shair17** [comment]
@CodeFlush popsplit.us has that because it has drawn the chat with html, in cigar is drawn with canvas, so first we would have to draw the chat with html and then with css, add the property overflow: auto

**Comment by Pollogy** [comment]
How to draw? Any help ... I dunno much

**Comment by ghost** [comment]
I guess not...

**Comment by bradennss** [comment]
lol i made popsplit

**Comment by bradennss** [comment]
why you guys tryna steal my IDEAS

**Comment by CodeFlush** [comment]
@chewythepig "Your Ideas" ????
Let Me state out times you have clearly stole someone else ideas

The Stroke in Leaderboard has been in gota for a long time

Gota.io : ( Original )
Leaderboard + Minimap : https://image.prntscr.com/image/a8G-FAV0S4y8Uhb03LlZSQ.png
Popsplit.us: Fake 
Leaderboard + Minimap : https://image.prntscr.com/image/WsSaST0nSKSx7Dy5cnT57Q.png


- The Party System which has been one Gota for ages.
- The Scrollable-Chat idea is stolen from gota.
- You website uses Gota.io skins, Given no credits or refrence to Gota, other than the name in the Buttoon "Gota Skins"



I used your website as an Example, I didn't say "Hey Guys, Popsplit.us has the unique feature that no other site in the world has, go steal his ideas, go inspect element the shit out of that" 
I just said " Popsplit.us Has this great feature that I like, It would be great if we could see this in the near future. 
How can you say we are stealing your ideas when you are just reproducing the feature of the game Gota.io. I was posting a suggestion, and Are you trying to say you were the first human being on earth to think of that idea? I am sure many sites has it. So, just because I used your site as an reference, to show an example. Don't Claim it as your idea, when you are clearly stealing someone elses.

**Comment by bradennss** [comment]
Yeah I didn’t actually put any thought into my response. You can slander my game all you want, but in all reality the entire game itself was “stolen”. So will yours and anyone else’s fork of Cigar. Also keep in mind that you **did** reference Popsplit when you could have focused on Gota.io, the original implementation of this UI system. @CodeFlush

**Comment by bradennss** [comment]
Also I like how you added “fake”, clever one.

**Comment by Luka967** [comment]
But you've ripped off agar.io in the first place so all you can do is criticize yourself. So can I in that matter

**Comment by Luka967** [comment]
And the first one to actually take off with HTML chat are the agarplus devs, not gota.

**Comment by bradennss** [comment]
@Luka967 you might as well tell everyone that, because I can assure you the majority of the people that have seen this repository had gone off and made their own clone with it. Also, thanks for the fun fact.

**Comment by cowpits** [comment]
@CodeFlush yeah scroll would be nice in chat. I compromised and change the number of message from 15 to 30.

**Comment by bradennss** [comment]
@Luka967 @cowpits @CodeFlush Let me know if you guys want me to write a scrollable chat to a fork and submit a merge request.

**Comment by cowpits** [comment]
@chewythepig I vote yes 👍

**Comment by Tetratrix** [comment]
yes!

**Comment by CodeFlush** [comment]
@chewythepig yes please and I agree with the above, sorry I went a lil harsh , cuz of the previous issue , but yes this would be great!
