### ISSUE TITLE
Apply except

### ISSUE THREAD

**Issue by PsycoYT** [Luka967/Cigar#28]
i think you must use that 

        `    var complex = this.wasComplexDrawing = settings.fastRenderMax = this.isPellet <= drawZoom,`

for less lag in the smoothrender..

i think you must use 

`
 mainCtx.lineWidth = this.isPellet ? 0 : this.size > 20 ? Math.max(this.size * .01, 10) : 0;
`

**instead**

` mainCtx.lineWidth = this.isEjected ? 0 : this.size > 20 ? Math.max(this.size * .01, 10) : 0;`

in agar.io the ejected mass is draw with a border

**Comment by Luka967** [comment]
First,
```js
var complex = this.wasComplexDrawing = settings.fastRenderMax = this.isPellet <= drawZoom
```
You're assigning a `Boolean` to `settings.fastRenderMax`, and it's a setting that the player changes. Not the code.
```js
settings.fastRenderMax = this.isPellet <= drawZoom
```
You're also comparing a `Boolean` to a `Number`.
So it ends up like this:
```js
// if it's a pellet
settings.fastRenderMax = 1 <= drawZoom
// if it's not a pellet
settings.fastRenderMax = 0 <= drawZoom
```
`drawZoom` is never zero, so if the cell isn't a pellet, `settings.fastRenderMax = false`.
And since (in most cases) players are larger than the pellets, and the cell drawing goes ascending in size,
```js
// It's always 0
settings.fastRenderMax = false = 0
```
And since `drawZoom` is never zero, you will always draw cells with points.

Second, I'm not going to draw an outline to ejected cells to save performance in an area with a lot of them.
